name: Flake8 Lint

on: [push, pull_request]

concurrency:
  group: flake8-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          update-pip: "true"
          max-line-length: "125"
          plugins: "flake8-bugbear"
