name: LLM Healthcheck

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  workflow_dispatch:
  release:
    types: [published, edited]
  schedule:
    - cron: '0 12 */7 * *'

concurrency:
  group: LLM-Checker-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  model-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies 
        working-directory: ./
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run model health check
        working-directory: ./
        run: |
          python -m pytest -v --color=yes test.py
