name: LLM Healthcheck

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  release:
    types: [published, edited]
  schedule:
    - cron: '0 0 * * *'

jobs:
  model-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies with poetry
        working-directory: ./
        run: |
          pip install pytest
          
      - name: Run model health check
        working-directory: ./
        run: |
          python -m pytest -v --color=yes test.py
